### PR TITLE
Re-write of some inventories, refactoring

### PR DESCRIPTION
**Pull request by al132**
Transition from the old IInventory system to IItemHandler in Mineral Sizer, Mineral
Analyzer, Lab Oven, and Chemical Extractor. Lots of refactoring for
readability and flexibility.

**Features/fixes:**
-Smart insertion and extraction, hoppers (and other inventory manipulators) will automatically insert into and pull from the correct slots. Now it is much easier to automate the entire ore process.
-tanks with fluid no longer stack
-Removed over 1000 lines of redundant/unnecessary code!

**Known bugs**
-I seemed to have broken the GUI processing animations, and i'm not quite sure how to fix this.

Naturally with such a big code change i've probably introduced a few other bugs, but I fixed all the other bugs that I found.

If you have any questions about anything i've done or how any of it works please feel free to ask!

### CODE REVIEW

**Comment by GlobbyPotato** [comment]
Hi, wow that's a lot of work! I gave a quick look at the code on eclipse and recognized some passages and simplifications but some of them require a level of knowledge I don't have to handle them mostrly about the slots handling.

I noticed an issues that I can't recognize yet: in mineral sizer and mineral analyzer the inductor slot is not accepting items.
I think the TileEntityReceiver works for the normal machine with only power but in the extractor and lab oven i've set to fill the rf bar first and then the power bar. I made a quick change duplicating that class,  adding my original code to look for rf and when at max for look for power and extending it on the tile entities.
I see you turned the consumable items (gear/tube/cylinder) into separate items. I thought to save ids by packing them into a single id and using an nbt as damage. Will remove the hover informations then being duplicated by durability.
Apparently the cooktime is not seen at the side in which the gui works? the tile.getfield(...) returns a division by zero so it seems not loading there. no idea too. I ,ay ask something as I hit a trouble. Thank you a lot for the time to look at it.

I will study some more the code, It looks quite efficient though.
Btw I see some //TODO and uncomplete/broken processes, are you going to fix more or should I go from there?

**Comment by al132** [comment]
I made a few more changes. Took care of the TODOs that I forgot about and fixed the inductor slot in the Mineral Sizer and Mineral analyzer,

Changing the consumable items into seperate items wasn't absolutely necessary, but it seemed like it was more trouble than it's worth for only a few items.

If you want me to explain anything specifically about the changes i've made i'd be glad to do so. I understand that it can be a bit tricky to wrap your head around it right away. It took me a while to understand how the system works.

**Comment by GlobbyPotato** [comment]
Ooh I totally missed the inductor was being called on the old stack.

Ok, will merge this for now and try to recognize every part. Meantime I did some work to simplify the gui scaled bars and on the Crawler Assembler TileEntity, I made some changes to make it more readable with an Enum and fixed the array loosing sync in it.

I got some troubles about the reorganization of the ClientProxy and CommonProxy and the blocks declaration, Sides always bugged me from the start. But I can figure out how to proceed by reading how they have been moved.
Something I'm stuck is in the nested TileEntity extentions. I have the general view but the whole StackHandler/TileEntityInv classes are off for me. Since I extend the highest class I guess I'll take them for good.

BTW in the BaseTileBlock can I remove the facing manipulation in setDefaultFacing, leaving only the worldIn.setBlockState... or is it functionale to the method? It came with the furnace code and only seems to mirror the model.

Thank you!

**Comment by al132** [comment]
The reorganization of the proxies and block declarations aren't absolutely necessary, but I suppose it's just a matter of preference. You can change them back to how you want if you'd like.

You can also remove setDefaultFacing if you want, I just figured that i'd keep it there because that's what you had in your classes.

Also: I think I know what is wrong with the cookTime problem. Since I moved maxCookTime to TileEntityLabOven I don't think that it is ever given a value, so be default it will be 0. Also, while we're on this topic. Some advice: It would make things much easier if you assigned the variables in their own classes rather than in ModConfig so that you know that the value is assigned when looking at the tile class.

For example:
In TileEntityChemicalExtractor: 
static int extractingFactor = ModConfig.extractingFactor (or whatever name)

Rather than:
In ModConfig:
 TileEntityChemicalExtractor.extractingFactor = config.get(...)  -while the value in the tile class isn't apparent.



I will try my best to explain the tile entity hierarchy:

1. **TileEntity**: Does nothing on it's own
2. **TileEntityBase**: Does anything TileEntity does and it overrides the methods for packet handling that is ever needed. Your mod doesn't really require those methods (getUpdatePacket,onDataPacket,getUpdateTag) currently, but I just use this class as a base for my other mods. It also the methods canInteractWith and getInventoryStackLimit which are both used by ContainerBase.

3.**TileEntityInv**: Does everything TileEntity and TileEntityBase does and it creates two inventories, an input and an output inventory and saves/loads the NBT tags for them. Anything that extends TileEntityInv will automatically have this saved as long as each class uses super.readFrom/writeTo NBT. The constructor asks how many slots each should have and creates them with that many slots. This is probably a new concept, because you are used to having one inventory, but this class creates two completely separate inventories. This isn't required, but it does make things easier.

This next part is a bit tricky and took me a while to understand; 4 handlers are created in the constructor: input, output, automationInput, and automationOutput. Most of them override methods directly inside of the constructor. I wasn't aware this could be done, and perhaps aren't either, but you can override the methods inside of a single object rather than having to make a class that overrides a method and create an instance of that. 

The insertItem method in **input** determines the rules for inserting items into the input inventory. Typically you'll want to do one of two things with the stack that is being inserted. Either you want to return it, which will cancel the inserting attempt and give the stack back to the player, or hopper, or whatever is trying to insert it. Or you can return super.insertItem.... which will do some validation checks for us. You can check what these are by looking at thismethod in the forge class ItemStackHandler.

The insertItem method in **output** always returns the inserting stack back to whatever is trying to insert, which basically means that neither a player nor any automation like a hopper can ever insert anything into it.

Then, there are the automationInput and automationOutput handlers that are wrapped around input and output. These are not separate inventories, infact they are the exact same inventories as input and output, they just have different "permissions" for inserting and extracting. When a player is interacting with an inventory they will be interacting with input and output, and if any other block is trying to interact with the inventory, like a hopper it will interact with automationInput and automationOutput, which are set in the getCapability method.

4.**TileEntityInvReceiver**: Does everything that the above classes do and it contains the energy and fuel handing methods that were identical in each of the Tile classes that I changed (Mineral Sizer, Lab Oven, etc).

5. TileEntityLabOven, TileEntityMineralSizer, etc: Do everything that all of the above classes do and their own stuff, of course.

Also, the class MachineStackHandler is just an extension of ItemStackHandler, which is an inventory sort of like IInventory slots, but it has some added utility methods for operations that are frequently done in your inventories like incrementing or decrementing slots.

I hope this helps :)

**Comment by GlobbyPotato** [comment]
It's true, it was not taking the getCookTime anymore. I removed it at all and replaced with the machine speed, which should be basiclly the purpose of the variable, getting the process bar to work again. 
Completed the consumables switch to the new format so all are damageable.

Thanks for the explaination, will focus on the input/output part the most

**Comment by GlobbyPotato** [comment]
Hi, I fisnished to check the entire mod for discrepancies.
I think I found an issue with the lab oven smelting. The recipe scroll buttons seem to cause the override of the ingredients check so you could smelt with wrong recipes. I made a change to make a brute check on each part of the recipe. Also did the same in the slot insertion part so each ingredient can be inserted only if its belonging recipe is selected, which should come handy with hoppers (the machine remains manual-oriented because of the tanks). In this way the recipe selector will be no longer a reminder for the player but an actual setup for the machine. Made a pastebin if you can check if it fits: http://pastebin.com/uj6EFwr2

One more thing, I noticed the GUI name string disappeared, Is the used method changed with this format? I added it manually because using the previous method can't seem to make the old getDisplayName().getUnformattedText() to read the "contained.labOven" from the lang file.

**Comment by al132** [comment]
I might take a look later, but for now if it works it's probably not a big deal. Perhaps in the future it would be betterto do what many other tech mods do and just register the fluids, add a few internal fluid tanks, and display it in JEI (the ender IO vat or the Forestry Fermenter are good examples) I'm not really familiar yet with how to handle fluids with forge's system (rather than just item NBT tags), but if you're interested I could help you look into it.

Adding the GUI name string manually is fine, the tiles I changed no longer implement IInventory, so they don't need to implement getDisplayName().

**Comment by GlobbyPotato** [comment]
Yeah it is working nicely, just making sure I was not missing a counterpart method on the way before adding more code.

About the fluids, the internal tank is possible at some point: at least unless there is an api like the rf to input/extract, my concept of tank is to store in a variable the quantity of fluid.., In 1.7.10 I had the acids as registered fluids and buckets and the oven had the tanks, though they were not of a real use outside the machine, hence the decision to keep them as nbt this time.
Tech mods are a muntain too high for me, that's why I rarely sneak into third party code. I will give a look for educational purposes but eventually I'll prefer to start only things I can understand.

**Pull request merged**
